from flask import Flask, request, render_template, redirect, session
import joblib
import os
import psycopg
from psycopg.rows import dict_row
import numpy as np
import pandas as pd
from datetime import date
from urllib.parse import urlencode
from sklearn.ensemble import IsolationForest


app = Flask(__name__)

app.secret_key = "smart-expense-secret-key"

DATABASE = "expense_intelligence.db"


# =========================================================
# LOAD TRAINED MODELS
# =========================================================

category_model = joblib.load(
    "models/category_model.pkl"
)

tfidf_vectorizer = joblib.load(
    "models/tfidf_vectorizer.pkl"
)

regression_model = joblib.load(
    "models/regression_model.pkl"
)


# =========================================================
# DATABASE CONNECTION
# =========================================================

def get_db_connection():

    database_url = os.environ.get("DATABASE_URL")

    if not database_url:
        raise RuntimeError("DATABASE_URL is not set")

    connection = psycopg.connect(
        database_url,
        row_factory=dict_row
    )

    return connection


# =========================================================
# CREATE USERS TABLE
# =========================================================

def create_users_table():

    connection = get_db_connection()

    connection.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)

    connection.commit()
    connection.close()


create_users_table()


# =========================================================
# CREATE EXPENSES TABLE
# =========================================================

def create_expenses_table():

    connection = get_db_connection()

    connection.execute("""
        CREATE TABLE IF NOT EXISTS expenses (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date TEXT NOT NULL,
            description TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            category TEXT,
            anomaly_status TEXT,
            user_id INTEGER
        )
    """)

    connection.commit()
    connection.close()


create_expenses_table()


# =========================================================
# ADD USER ID TO EXISTING EXPENSES TABLE
# =========================================================

def add_user_id_column():

    connection = get_db_connection()

    connection.execute("""
        ALTER TABLE expenses
        ADD COLUMN IF NOT EXISTS user_id INTEGER
    """)

    connection.commit()
    connection.close()


add_user_id_column()


# =========================================================
# PERSONALIZED ISOLATION FOREST
# CHECK NEW TRANSACTION
# =========================================================

def final_anomaly_check(history, new_amount):

    history = np.array(
        history,
        dtype=float
    )

    # New transaction needs at least
    # 10 previous personal expenses
    if len(history) < 10:

        return "Not enough history"

    history_data = pd.DataFrame({

        "Amount": history,

        "Amount_Log": np.log1p(history)

    })

    model = IsolationForest(

        n_estimators=200,

        contamination="auto",

        random_state=42

    )

    model.fit(history_data)

    new_data = pd.DataFrame({

        "Amount": [new_amount],

        "Amount_Log": [
            np.log1p(new_amount)
        ]

    })

    score = model.decision_function(
        new_data
    )[0]

    history_scores = model.decision_function(
        history_data
    )

    # Changed from 5% to 15%
    # This allows multiple unusual transactions
    score_limit = np.percentile(
        history_scores,
        15
    )

    if score < score_limit:

        return "Unusual"

    return "Normal"


# =========================================================
# CHECK EXISTING TRANSACTIONS
# =========================================================

def update_existing_anomalies(user_id):

    connection = get_db_connection()

    transactions = connection.execute(
        """
        SELECT
            id,
            amount
        FROM expenses
        WHERE user_id = %s
        ORDER BY date, id
        """,
        (user_id,)
    ).fetchall()

    # Existing transactions can be checked
    # when the user has at least 5 expenses
    if len(transactions) < 5:

        connection.execute(
            """
            UPDATE expenses
            SET anomaly_status = 'Normal'
            WHERE user_id = %s
            """,
            (user_id,)
        )

        connection.commit()

        connection.close()

        return

    amounts = [
        float(row["amount"])
        for row in transactions
    ]

    # Check every existing transaction
    for index, transaction in enumerate(transactions):

        transaction_id = transaction["id"]

        transaction_amount = float(
            transaction["amount"]
        )

        # Remove the current transaction
        # from its own history
        history = (
            amounts[:index]
            + amounts[index + 1:]
        )

        # Need at least 4 other expenses
        if len(history) < 4:

            anomaly_status = "Normal"

        else:

            history_array = np.array(
                history,
                dtype=float
            )

            history_data = pd.DataFrame({

                "Amount": history_array,

                "Amount_Log": np.log1p(
                    history_array
                )

            })

            model = IsolationForest(

                n_estimators=200,

                contamination="auto",

                random_state=42

            )

            model.fit(history_data)

            transaction_data = pd.DataFrame({

                "Amount": [
                    transaction_amount
                ],

                "Amount_Log": [
                    np.log1p(
                        transaction_amount
                    )
                ]

            })

            transaction_score = (
                model.decision_function(
                    transaction_data
                )[0]
            )

            history_scores = (
                model.decision_function(
                    history_data
                )
            )

            # Changed from 5% to 15%
            # This allows multiple unusual transactions
            score_limit = np.percentile(
                history_scores,
                15
            )

            if transaction_score < score_limit:

                anomaly_status = "Unusual"

            else:

                anomaly_status = "Normal"

        connection.execute(
            """
            UPDATE expenses
            SET anomaly_status = %s
            WHERE id = %s
            AND user_id = %s
            """,
            (
                anomaly_status,
                transaction_id,
                user_id
            )
        )

    connection.commit()

    connection.close()


# =========================================================
# NEXT MONTH PREDICTION
# =========================================================

def predict_next_month(user_expenses):

    data = user_expenses.copy()

    data["date"] = pd.to_datetime(
        data["date"]
    )

    current_month = (
        data["date"].max().to_period("M")
    )

    current_data = data[
        data["date"].dt.to_period("M")
        == current_month
    ]

    current_total = current_data[
        "amount"
    ].sum()

    previous_month = current_month - 1

    previous_data = data[
        data["date"].dt.to_period("M")
        == previous_month
    ]

    previous_month_total = previous_data[
        "amount"
    ].sum()

    transaction_count = len(
        current_data
    )

    previous_transaction_count = len(
        previous_data
    )

    # Need at least 3 transactions
    # in the current month
    if transaction_count < 3:

        return {

            "current_total":
                current_total,

            "previous_month_total":
                previous_month_total,

            "prediction":
                None,

            "method":
                "Not enough expense data"
        }

    # =====================================================
    # HANDLE PREVIOUS MONTH
    # =====================================================

    if previous_data.empty:

        # Previous month is unavailable.
        # Use current month as the reference
        # instead of sending zero to the model.
        model_previous_spending = current_total

        model_previous_transaction_count = (
            transaction_count
        )

        method = (
            "Random Forest using "
            "current-month spending "
            "(previous month unavailable)"
        )

    else:

        # Previous month exists.
        # Use the actual previous-month values.
        model_previous_spending = (
            previous_month_total
        )

        model_previous_transaction_count = (
            previous_transaction_count
        )

        method = (
            "Random Forest using "
            "current + previous month"
        )

    # =====================================================
    # CREATE MODEL INPUT
    # =====================================================

    features = pd.DataFrame([{

        "monthly_spending":
            current_total,

        "previous_month_spending":
            model_previous_spending,

        "transaction_count":
            transaction_count,

        "previous_transaction_count":
            model_previous_transaction_count,

        "month":
            current_month.month

    }])

    print("\nPrediction features:")
    print(features)

    # =====================================================
    # RANDOM FOREST PREDICTION
    # =====================================================

    prediction = regression_model.predict(
        features
    )[0]

    prediction = max(
        0,
        float(prediction)
    )

    return {

        "current_total":
            current_total,

        "previous_month_total":
            previous_month_total,

        "prediction":
            prediction,

        "method":
            method
    }


# =========================================================
# HOME
# =========================================================

@app.route("/")
def home():

    if "user_id" not in session:

        return redirect("/login")

    return redirect("/dashboard")


# =========================================================
# LOGIN
# =========================================================

@app.route(
    "/login",
    methods=["GET", "POST"]
)
def login():

    if request.method == "POST":

        username = request.form["username"]

        password = request.form["password"]

        connection = get_db_connection()

        user = connection.execute(
            """
            SELECT id, username
            FROM users
            WHERE username = %s
            AND password = %s
            """,
            (
                username,
                password
            )
        ).fetchone()

        connection.close()

        if user:

            session["user_id"] = user["id"]

            session["username"] = user["username"]

            return redirect("/dashboard")

        return render_template(
            "login.html",
            error="Invalid username or password"
        )

    return render_template(
        "login.html"
    )


# =========================================================
# SIGN UP
# =========================================================

@app.route(
    "/signup",
    methods=["GET", "POST"]
)
def signup():

    if request.method == "POST":

        username = request.form["username"]

        password = request.form["password"]

        connection = get_db_connection()

        existing_user = connection.execute(
            """
            SELECT id
            FROM users
            WHERE username = %s
            """,
            (username,)
        ).fetchone()

        if existing_user:

            connection.close()

            return render_template(
                "signup.html",
                error="Username already exists"
            )

        connection.execute(
            """
            INSERT INTO users
            (
                username,
                password
            )
            VALUES (%s, %s)
            """,
            (
                username,
                password
            )
        )

        connection.commit()

        connection.close()

        return redirect("/login")

    return render_template(
        "signup.html"
    )


# =========================================================
# FORGOT PASSWORD
# =========================================================

@app.route(
    "/forgot-password",
    methods=["GET", "POST"]
)
def forgot_password():

    if request.method == "POST":

        username = request.form["username"]

        new_password = request.form["new_password"]

        confirm_password = request.form["confirm_password"]

        if new_password != confirm_password:

            return render_template(
                "forgot_password.html",
                error="Passwords do not match."
            )

        connection = get_db_connection()

        user = connection.execute(
            """
            SELECT id
            FROM users
            WHERE username = %s
            """,
            (username,)
        ).fetchone()

        if user is None:

            connection.close()

            return render_template(
                "forgot_password.html",
                error="Username not found."
            )

        connection.execute(
            """
            UPDATE users
            SET password = %s
            WHERE id = %s
            """,
            (
                new_password,
                user["id"]
            )
        )

        connection.commit()

        connection.close()

        return render_template(
            "forgot_password.html",
            success="Password reset successfully. You can now login."
        )

    return render_template(
        "forgot_password.html"
    )


# =========================================================
# LOGOUT
# =========================================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect("/login")


# =========================================================
# RESULT PAGE
# =========================================================

@app.route("/result")
def result():

    if "user_id" not in session:

        return redirect("/login")

    return render_template(

        "result.html",

        description=request.args.get(
            "description"
        ),

        amount=request.args.get(
            "amount"
        ),

        category=request.args.get(
            "category"
        ),

        payment_method=request.args.get(
            "payment_method"
        ),

        time_of_day=request.args.get(
            "time_of_day"
        ),

        anomaly_status=request.args.get(
            "anomaly_status"
        )
    )


# =========================================================
# DASHBOARD
# =========================================================

@app.route("/dashboard")
def dashboard():

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    connection = get_db_connection()

    expenses = connection.execute(
        """
        SELECT *
        FROM expenses
        WHERE user_id = %s
        ORDER BY date
        """,
        (user_id,)
    ).fetchall()

    if expenses:

        user_expenses = pd.DataFrame(
            [dict(row) for row in expenses]
        )

    else:

        user_expenses = pd.DataFrame(
            columns=[
                "id",
                "date",
                "description",
                "amount",
                "category",
                "anomaly_status",
                "user_id"
            ]
        )

    total_spending = connection.execute(
        """
        SELECT COALESCE(SUM(amount), 0) AS total_spending
        FROM expenses
        WHERE user_id = %s
        """,
        (user_id,)
    ).fetchone()["total_spending"]

    current_month = date.today().strftime(
        "%Y-%m"
    )

    this_month = connection.execute(
        """
        SELECT COALESCE(SUM(amount), 0) AS total_spending
        FROM expenses
        WHERE user_id = %s
        AND date LIKE %s
        """,
        (
            user_id,
            current_month + "%"
        )
    ).fetchone()["total_spending"]

    monthly_spending = connection.execute(
        """
        SELECT
            substr(date, 1, 7) AS month,
            SUM(amount) AS total
        FROM expenses
        WHERE user_id = %s
        GROUP BY month
        ORDER BY month
        """,
        (user_id,)
    ).fetchall()

    last_month_spending = None

    previous_month = (
        pd.Period(
            current_month,
            freq="M"
        ) - 1
    )

    previous_month_str = str(
        previous_month
    )

    last_month_result = connection.execute(
        """
        SELECT COALESCE(SUM(amount), 0) AS total_spending
        FROM expenses
        WHERE user_id = %s
        AND date LIKE %s
        """,
        (
            user_id,
            previous_month_str + "%"
        )
    ).fetchone()["total_spending"]

    if last_month_result > 0:

        last_month_spending = (
            last_month_result
        )

    if last_month_spending is not None:

        spending_change = (
            this_month
            - last_month_spending
        )

        spending_change_percentage = (
            spending_change
            / last_month_spending
        ) * 100

    else:

        spending_change = None

        spending_change_percentage = None

    unusual_expenses = connection.execute(
        """
        SELECT COUNT(*) AS count
        FROM expenses
        WHERE user_id = %s
        AND anomaly_status = 'Unusual'
        """,
        (user_id,)
    ).fetchone()["count"]

    category_spending = connection.execute(
        """
        SELECT
            category,
            SUM(amount) AS total
        FROM expenses
        WHERE user_id = %s
        GROUP BY category
        ORDER BY total DESC
        """,
        (user_id,)
    ).fetchall()

    predicted_next_month = None

    prediction_method = None

    if not user_expenses.empty:

        prediction_result = (
            predict_next_month(
                user_expenses
            )
        )

        predicted_next_month = (
            prediction_result["prediction"]
        )

        prediction_method = (
            prediction_result["method"]
        )

    if user_expenses.empty:

        spending_insight = (
            "Add some expenses to start "
            "getting spending insights."
        )

    elif predicted_next_month is None:

        spending_insight = (
            "Add a few more expenses to get "
            "a more reliable next-month prediction."
        )

    elif last_month_spending is not None:

        if spending_change > 0:

            spending_insight = (
                f"Your spending increased by "
                f"{abs(spending_change_percentage):.2f}% "
                f"compared with last month."
            )

        elif spending_change < 0:

            spending_insight = (
                f"Your spending decreased by "
                f"{abs(spending_change_percentage):.2f}% "
                f"compared with last month."
            )

        else:

            spending_insight = (
                "Your spending is almost the "
                "same as last month."
            )

    elif this_month > 0:

        prediction_change_percentage = (
            (
                predicted_next_month
                - this_month
            )
            / this_month
        ) * 100

        if prediction_change_percentage > 1:

            spending_insight = (
                f"Your predicted next-month "
                f"spending is "
                f"{prediction_change_percentage:.2f}% "
                f"higher than this month."
            )

        elif prediction_change_percentage < -1:

            spending_insight = (
                f"Your predicted next-month "
                f"spending is "
                f"{abs(prediction_change_percentage):.2f}% "
                f"lower than this month."
            )

        else:

            spending_insight = (
                "Your predicted next-month "
                "spending is nearly the same "
                "as this month."
            )

    else:

        spending_insight = (
            "Keep recording expenses to get "
            "more personalized spending insights."
        )

    recent_transactions = connection.execute(
        """
        SELECT
            id,
            date,
            description,
            amount,
            category,
            anomaly_status
        FROM expenses
        WHERE user_id = %s
        ORDER BY id DESC
        LIMIT 5
        """,
        (user_id,)
    ).fetchall()

    recent_unusual = connection.execute(
        """
        SELECT
            date,
            description,
            amount,
            category
        FROM expenses
        WHERE user_id = %s
        AND anomaly_status = 'Unusual'
        ORDER BY id DESC
        LIMIT 5
        """,
        (user_id,)
    ).fetchall()

    connection.close()

    return render_template(

        "dashboard.html",

        username=session.get(
            "username"
        ),

        total_spending=
            total_spending,

        last_month_spending=
            last_month_spending,

        this_month=
            this_month,

        spending_change=
            spending_change,

        spending_change_percentage=
            spending_change_percentage,

        spending_insight=
            spending_insight,

        unusual_expenses=
            unusual_expenses,

        category_spending=
            category_spending,

        monthly_spending=
            monthly_spending,

        recent_transactions=
            recent_transactions,

        recent_unusual=
            recent_unusual,

        predicted_next_month=
            predicted_next_month,

        prediction_method=
            prediction_method
    )


# =========================================================
# PREDICTION & INSIGHTS PAGE
# =========================================================

@app.route("/prediction")
def prediction():

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    connection = get_db_connection()

    expenses = connection.execute(
        """
        SELECT *
        FROM expenses
        WHERE user_id = %s
        ORDER BY date
        """,
        (user_id,)
    ).fetchall()

    if expenses:

        user_expenses = pd.DataFrame(
            [dict(row) for row in expenses]
        )

    else:

        user_expenses = pd.DataFrame(
            columns=[
                "id",
                "date",
                "description",
                "amount",
                "category",
                "anomaly_status",
                "user_id"
            ]
        )

    predicted_next_month = None

    prediction_method = None

    if not user_expenses.empty:

        prediction_result = (
            predict_next_month(
                user_expenses
            )
        )

        this_month = (
            prediction_result[
                "current_total"
            ]
        )

        previous_total = (
            prediction_result[
                "previous_month_total"
            ]
        )

        predicted_next_month = (
            prediction_result[
                "prediction"
            ]
        )

        prediction_method = (
            prediction_result[
                "method"
            ]
        )

        if previous_total > 0:

            last_month_spending = (
                previous_total
            )

        else:

            last_month_spending = None

    else:

        this_month = 0

        last_month_spending = None

    spending_change = None

    spending_change_percentage = None

    if (
        last_month_spending is not None
        and last_month_spending > 0
    ):

        spending_change = (
            this_month
            - last_month_spending
        )

        spending_change_percentage = (
            spending_change
            / last_month_spending
        ) * 100

    if user_expenses.empty:

        spending_insight = (
            "Add some expenses to start "
            "getting spending insights."
        )

    elif predicted_next_month is None:

        spending_insight = (
            "Add a few more expenses to get "
            "a more reliable next-month prediction."
        )

    elif last_month_spending is not None:

        if spending_change > 0:

            spending_insight = (
                f"Your spending increased by "
                f"{abs(spending_change_percentage):.2f}% "
                f"compared with last month."
            )

        elif spending_change < 0:

            spending_insight = (
                f"Your spending decreased by "
                f"{abs(spending_change_percentage):.2f}% "
                f"compared with last month."
            )

        else:

            spending_insight = (
                "Your spending is almost the "
                "same as last month."
            )

    elif this_month > 0:

        prediction_change_percentage = (
            (
                predicted_next_month
                - this_month
            )
            / this_month
        ) * 100

        if prediction_change_percentage > 1:

            spending_insight = (
                f"Your predicted next-month "
                f"spending is "
                f"{prediction_change_percentage:.2f}% "
                f"higher than this month."
            )

        elif prediction_change_percentage < -1:

            spending_insight = (
                f"Your predicted next-month "
                f"spending is "
                f"{abs(prediction_change_percentage):.2f}% "
                f"lower than this month."
            )

        else:

            spending_insight = (
                "Your predicted next-month "
                "spending is nearly the same "
                "as this month."
            )

    else:

        spending_insight = (
            "Keep recording expenses to get "
            "more personalized spending insights."
        )

    connection.close()

    return render_template(

        "prediction.html",

        username=session.get(
            "username"
        ),

        this_month=
            this_month,

        last_month_spending=
            last_month_spending,

        predicted_next_month=
            predicted_next_month,

        spending_change=
            spending_change,

        spending_change_percentage=
            spending_change_percentage,

        spending_insight=
            spending_insight,

        prediction_method=
            prediction_method
    )


# =========================================================
# HISTORY PAGE
# =========================================================

@app.route("/history")
def history():

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    connection = get_db_connection()

    monthly_spending = connection.execute(
        """
        SELECT
            substr(date, 1, 7) AS month,
            SUM(amount) AS total_spending,
            COUNT(*) AS transaction_count
        FROM expenses
        WHERE user_id = %s
        GROUP BY month
        ORDER BY month DESC
        """,
        (user_id,)
    ).fetchall()

    connection.close()

    return render_template(
        "history.html",
        monthly_data=monthly_spending,
        username=session.get(
            "username"
        )
    )


# =========================================================
# HISTORY - MONTH DETAILS
# =========================================================

@app.route("/history/<month>")
def history_month(month):

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    connection = get_db_connection()

    total_spending = connection.execute(
        """
        SELECT COALESCE(SUM(amount), 0) AS total_spending
        FROM expenses
        WHERE user_id = %s
        AND date LIKE %s
        """,
        (
            user_id,
            month + "%"
        )
    ).fetchone()["total_spending"]

    transactions = connection.execute(
        """
        SELECT
            id,
            date,
            description,
            amount,
            category,
            anomaly_status
        FROM expenses
        WHERE user_id = %s
        AND date LIKE %s
        ORDER BY date DESC, id DESC
        """,
        (
            user_id,
            month + "%"
        )
    ).fetchall()

    connection.close()

    return render_template(

        "history_month.html",

        month=month,

        total_spending=
            total_spending,

        transactions=
            transactions,

        username=session.get(
            "username"
        )
    )


# =========================================================
# ALL / RECENT TRANSACTIONS
# =========================================================

@app.route("/transactions")
def transactions():

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    connection = get_db_connection()

    all_transactions = connection.execute(
        """
        SELECT
            id,
            date,
            description,
            amount,
            category,
            anomaly_status
        FROM expenses
        WHERE user_id = %s
        ORDER BY date DESC, id DESC
        """,
        (user_id,)
    ).fetchall()

    connection.close()

    return render_template(

        "transactions.html",

        transactions=
            all_transactions,

        username=session.get(
            "username"
        )
    )


# =========================================================
# REMOVE EXPENSE
# =========================================================

@app.route(
    "/remove-expense/<int:expense_id>",
    methods=["POST"]
)
def remove_expense(expense_id):

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    connection = get_db_connection()

    # Delete only the selected expense
    # belonging to the logged-in user
    connection.execute(
        """
        DELETE FROM expenses
        WHERE id = %s
        AND user_id = %s
        """,
        (
            expense_id,
            user_id
        )
    )

    connection.commit()

    connection.close()

    # =====================================================
    # PERFORMANCE CHANGE
    # =====================================================
    # We intentionally do NOT call
    # update_existing_anomalies() here.
    #
    # This prevents Isolation Forest from being
    # recalculated for every remaining transaction
    # whenever an expense is removed.
    #
    # The existing anomaly calculation is still
    # available on the Unusual Transactions page.
    # =====================================================

    return redirect("/transactions")


# =========================================================
# UNUSUAL TRANSACTIONS
# =========================================================

@app.route("/unusual")
def unusual():

    if "user_id" not in session:

        return redirect("/login")

    user_id = session["user_id"]

    # Existing anomaly logic remains unchanged.
    # It is recalculated only when the user opens
    # the Unusual Transactions page.
    update_existing_anomalies(user_id)

    connection = get_db_connection()

    unusual_transactions = connection.execute(
        """
        SELECT
            id,
            date,
            description,
            amount,
            category,
            anomaly_status
        FROM expenses
        WHERE user_id = %s
        AND anomaly_status = 'Unusual'
        ORDER BY date DESC, id DESC
        """,
        (user_id,)
    ).fetchall()

    connection.close()

    return render_template(

        "unusual.html",

        transactions=
            unusual_transactions,

        username=session.get(
            "username"
        )
    )


# =========================================================
# ADD EXPENSE
# =========================================================

@app.route(
    "/add-expense",
    methods=["GET", "POST"]
)
def add_expense():

    if "user_id" not in session:

        return redirect("/login")

    if request.method == "GET":

        return render_template(
            "index.html",
            username=session.get("username")
        )

    user_id = session["user_id"]

    # =====================================================
    # GET EXPENSE DATE FROM FORM
    # =====================================================

    expense_date = request.form[
        "expense_date"
    ]

    description = request.form[
        "description"
    ]

    amount = float(
        request.form["amount"]
    )

    payment_method = request.form[
        "payment_method"
    ]

    time_of_day = request.form[
        "time_of_day"
    ]

    # =====================================================
    # CATEGORY PREDICTION
    # =====================================================

    description_tfidf = (
        tfidf_vectorizer.transform(
            [description]
        )
    )

    category = (
        category_model.predict(
            description_tfidf
        )[0]
    )

    # =====================================================
    # GET USER HISTORY
    # =====================================================

    connection = get_db_connection()

    previous_expenses = connection.execute(
        """
        SELECT amount
        FROM expenses
        WHERE user_id = %s
        ORDER BY date, id
        """,
        (user_id,)
    ).fetchall()

    user_history = [
        row["amount"]
        for row in previous_expenses
    ]

    # =====================================================
    # CHECK NEW EXPENSE
    # =====================================================

    anomaly_status = final_anomaly_check(
        user_history,
        amount
    )

    if anomaly_status == "Not enough history":

        anomaly_status = "Normal"

    # =====================================================
    # STORE NEW EXPENSE
    # =====================================================

    connection.execute(
        """
        INSERT INTO expenses
        (
            date,
            description,
            amount,
            category,
            anomaly_status,
            user_id
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            expense_date,
            description,
            amount,
            category,
            anomaly_status,
            user_id
        )
    )

    connection.commit()

    connection.close()

    # =====================================================
    # PERFORMANCE CHANGE
    # =====================================================
    # We intentionally do NOT call
    # update_existing_anomalies() here.
    #
    # The new expense already has its anomaly status
    # from final_anomaly_check().
    #
    # This prevents Isolation Forest from being
    # recalculated for every previous transaction
    # whenever a new expense is added.
    # =====================================================

    # =====================================================
    # RESULT PAGE
    # =====================================================

    result_data = {

        "description":
            description,

        "amount":
            amount,

        "category":
            category,

        "payment_method":
            payment_method,

        "time_of_day":
            time_of_day,

        "anomaly_status":
            anomaly_status
    }

    result_url = (
        "/result?"
        + urlencode(result_data)
    )

    return redirect(
        result_url
    )


# =========================================================
# RUN APPLICATION
# =========================================================

if __name__ == "__main__":

    app.run(
        debug=True
    )