import sqlite3
import os
import psycopg


# =========================================================
# CONNECT TO LOCAL SQLITE DATABASE
# =========================================================

sqlite_connection = sqlite3.connect(
    "expense_intelligence.db"
)

sqlite_connection.row_factory = sqlite3.Row


# =========================================================
# CONNECT TO SUPABASE POSTGRESQL
# =========================================================

database_url = os.environ.get("DATABASE_URL")

if not database_url:
    raise RuntimeError("DATABASE_URL is not set")

postgres_connection = psycopg.connect(
    database_url
)


# =========================================================
# CREATE TABLES IN SUPABASE
# =========================================================

postgres_connection.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL
    )
""")

postgres_connection.execute("""
    CREATE TABLE IF NOT EXISTS expenses (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date TEXT NOT NULL,
        description TEXT NOT NULL,
        amount DOUBLE PRECISION NOT NULL,
        category TEXT,
        anomaly_status TEXT,
        user_id INTEGER
    )
""")

postgres_connection.commit()


# =========================================================
# SAFETY CHECK
# =========================================================

existing_users = postgres_connection.execute(
    "SELECT COUNT(*) FROM users"
).fetchone()[0]

existing_expenses = postgres_connection.execute(
    "SELECT COUNT(*) FROM expenses"
).fetchone()[0]

if existing_users > 0 or existing_expenses > 0:

    sqlite_connection.close()
    postgres_connection.close()

    raise RuntimeError(
        "Supabase already contains data. "
        "Migration stopped to prevent duplicate data."
    )


# =========================================================
# READ EXISTING SQLITE DATA
# =========================================================

users = sqlite_connection.execute("""
    SELECT
        id,
        username,
        password
    FROM users
    ORDER BY id
""").fetchall()


expenses = sqlite_connection.execute("""
    SELECT
        id,
        date,
        description,
        amount,
        category,
        anomaly_status,
        user_id
    FROM expenses
    ORDER BY id
""").fetchall()


print(f"Found {len(users)} users in SQLite.")
print(f"Found {len(expenses)} expenses in SQLite.")


# =========================================================
# COPY USERS
# =========================================================

for user in users:

    postgres_connection.execute(
        """
        INSERT INTO users
        (
            id,
            username,
            password
        )
        VALUES (%s, %s, %s)
        """,
        (
            user["id"],
            user["username"],
            user["password"]
        )
    )


# =========================================================
# COPY EXPENSES
# =========================================================

for expense in expenses:

    postgres_connection.execute(
        """
        INSERT INTO expenses
        (
            id,
            date,
            description,
            amount,
            category,
            anomaly_status,
            user_id
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """,
        (
            expense["id"],
            expense["date"],
            expense["description"],
            expense["amount"],
            expense["category"],
            expense["anomaly_status"],
            expense["user_id"]
        )
    )


# =========================================================
# FIX ID SEQUENCES
# =========================================================

postgres_connection.execute("""
    SELECT setval(
        pg_get_serial_sequence('users', 'id'),
        COALESCE((SELECT MAX(id) FROM users), 1),
        true
    )
""")

postgres_connection.execute("""
    SELECT setval(
        pg_get_serial_sequence('expenses', 'id'),
        COALESCE((SELECT MAX(id) FROM expenses), 1),
        true
    )
""")


# =========================================================
# SAVE MIGRATION
# =========================================================

postgres_connection.commit()


# =========================================================
# VERIFY COUNTS
# =========================================================

new_users = postgres_connection.execute(
    "SELECT COUNT(*) FROM users"
).fetchone()[0]

new_expenses = postgres_connection.execute(
    "SELECT COUNT(*) FROM expenses"
).fetchone()[0]


print()
print("Migration completed.")
print(f"Supabase users: {new_users}")
print(f"Supabase expenses: {new_expenses}")


# =========================================================
# CLOSE CONNECTIONS
# =========================================================

sqlite_connection.close()
postgres_connection.close()